In [2]:
import pandas as pd
import glob
import numpy as np
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
import matplotlib.pyplot as plt

In [8]:
glob.glob('./*/')

['.\\anaconda3\\',
 '.\\AppData\\',
 '.\\Application Data\\',
 '.\\Contacts\\',
 '.\\Cookies\\',
 '.\\Desktop\\',
 '.\\Documents\\',
 '.\\Downloads\\',
 '.\\Favorites\\',
 '.\\Links\\',
 '.\\Local Settings\\',
 '.\\Menu Démarrer\\',
 '.\\Mes documents\\',
 '.\\Microsoft\\',
 '.\\minio\\',
 '.\\mlartifacts\\',
 '.\\mlruns\\',
 '.\\Modèles\\',
 '.\\Music\\',
 '.\\OneDrive\\',
 '.\\OneDrive - Université de Technologie de Troyes\\',
 '.\\Pictures\\',
 '.\\Postman\\',
 '.\\PycharmProjects\\',
 '.\\Recent\\',
 '.\\Saved Games\\',
 '.\\Searches\\',
 '.\\SendTo\\',
 '.\\tf_model\\',
 '.\\Videos\\',
 '.\\VirtualBox VMs\\',
 ".\\Voisinage d'impression\\",
 '.\\Voisinage réseau\\']

In [9]:
%pwd

'C:\\Users\\plele'

# Mobilité

## Bornes de recharge électrique en France

https://public.opendatasoft.com/explore/dataset/mobilityref-france-irve-220/information/?disjunctive.nom_amenageur&disjunctive.nom_operateur&disjunctive.nom_enseigne&disjunctive.implantation_station&disjunctive.prise_type_ef&disjunctive.prise_type_2&disjunctive.prise_type_combo_ccs&disjunctive.prise_type_chademo&disjunctive.prise_type_autre&disjunctive.gratuit&disjunctive.paiement_acte&disjunctive.paiement_cb&disjunctive.paiement_autre&disjunctive.condition_acces&disjunctive.reservation&disjunctive.raccordement&disjunctive.com_arm_name&disjunctive.nom_epci&disjunctive.dep_name&disjunctive.reg_name&basemap=jawg.light&location=2,0.08175,8.27828&dataChart=eyJxdWVyaWVzIjpbeyJjaGFydHMiOlt7InR5cGUiOiJsaW5lIiwiZnVuYyI6IkNPVU5UIiwieUF4aXMiOiJuYnJlX3BkYyIsInNjaWVudGlmaWNEaXNwbGF5Ijp0cnVlLCJjb2xvciI6IiNGRjUxNUEifV0sInhBeGlzIjoiZGF0ZV9taXNlX2VuX3NlcnZpY2UiLCJtYXhwb2ludHMiOm51bGwsInRpbWVzY2FsZSI6Im1vbnRoIiwic29ydCI6IiIsImNvbmZpZyI6eyJkYXRhc2V0IjoibW9iaWxpdHlyZWYtZnJhbmNlLWlydmUtMjIwIiwib3B0aW9ucyI6eyJkaXNqdW5jdGl2ZS5ub21fYW1lbmFnZXVyIjp0cnVlLCJkaXNqdW5jdGl2ZS5ub21fb3BlcmF0ZXVyIjp0cnVlLCJkaXNqdW5jdGl2ZS5ub21fZW5zZWlnbmUiOnRydWUsImRpc2p1bmN0aXZlLmltcGxhbnRhdGlvbl9zdGF0aW9uIjp0cnVlLCJkaXNqdW5jdGl2ZS5wcmlzZV90eXBlX2VmIjp0cnVlLCJkaXNqdW5jdGl2ZS5wcmlzZV90eXBlXzIiOnRydWUsImRpc2p1bmN0aXZlLnByaXNlX3R5cGVfY29tYm9fY2NzIjp0cnVlLCJkaXNqdW5jdGl2ZS5wcmlzZV90eXBlX2NoYWRlbW8iOnRydWUsImRpc2p1bmN0aXZlLnByaXNlX3R5cGVfYXV0cmUiOnRydWUsImRpc2p1bmN0aXZlLmdyYXR1aXQiOnRydWUsImRpc2p1bmN0aXZlLnBhaWVtZW50X2FjdGUiOnRydWUsImRpc2p1bmN0aXZlLnBhaWVtZW50X2NiIjp0cnVlLCJkaXNqdW5jdGl2ZS5wYWllbWVudF9hdXRyZSI6dHJ1ZSwiZGlzanVuY3RpdmUuY29uZGl0aW9uX2FjY2VzIjp0cnVlLCJkaXNqdW5jdGl2ZS5yZXNlcnZhdGlvbiI6dHJ1ZSwiZGlzanVuY3RpdmUucmFjY29yZGVtZW50Ijp0cnVlLCJkaXNqdW5jdGl2ZS5jb21fYXJtX25hbWUiOnRydWUsImRpc2p1bmN0aXZlLm5vbV9lcGNpIjp0cnVlLCJkaXNqdW5jdGl2ZS5kZXBfbmFtZSI6dHJ1ZSwiZGlzanVuY3RpdmUucmVnX25hbWUiOnRydWV9fX1dLCJkaXNwbGF5TGVnZW5kIjp0cnVlLCJhbGlnbk1vbnRoIjp0cnVlLCJ0aW1lc2NhbGUiOiIifQ%3D%3D

In [ ]:
df_elec = pd.read_csv(glob.glob('.\\Fichier consolidé des Bornes de Recharge pour Véhicules Électriques (IRVE) – schéma 2.2.0\\*.*')[0],sep=';')

In [ ]:
df_elec.shape

In [ ]:
df_elec[:3]

In [ ]:
df_elec.columns

In [ ]:
selected_col = ['Nom aménageur', 
       'Nom opérateur', 
       'Nom enseigne', 'ID station itinérance', 'ID station local',
       'Nom station', 'Implantation station', 'Adresse station',
       'Code INSEE commune', 'Coordonnées', 'Nombre Points de charge',
       'ID PDC itinérance', 'ID PDC local', 'Puissance nominale',
       'Prise type E/F', 'Prise type 2', 'Prise type combo ccs',
       'Prise type chademo', 'Prise type autre', 'Gratuit', 'Paiement acte',
       'Paiement CB', 'Paiement autre', 'Tarification', 'Condition accès',
       'Réservation', 'Horaires', 'Accessibilité PMR', 'Restriction gabarit',
       'Station deux roues', 'Raccordement', 'Num PDL', 
                'Date mise en service',
       'Observations', 'Date de Mise à Jour', 'cable_t2_attache',
       'Dernière modification', 
       'consolidated_longitude', 'consolidated_latitude',
       'consolidated_code_postal', 'consolidated_commune',
       'consolidated_is_lon_lat_correct',
       'coord', 'longitude', 'latitude',
       'point_geo', '''Nom de la commune ou de l'arrondissement municipal''',
       '''Code de la commune ou de l'arrondissement''', 'Code EPCI',
       '''Nom de l'EPCI''', 'Code Officiel Département',
       'Nom Officiel Département', 'Code Officiel Région',
       'Nom Officiel Région']

In [ ]:
df_elec.dtypes

In [ ]:
df_elec.describe()

In [ ]:
df_elec.duplicated(subset=['ID station itinérance'],keep=False)

In [ ]:
for c in df_elec.columns:
    print(c)
    print(df_elec[c].unique().shape[0], sum(df_elec[c].isna()), df_elec.shape[0])
    # print(df_elec[c].unique())
    print('-----------------------------')

In [ ]:
for c in df_elec.columns:
    print(c)
    print(df_elec[c].unique().shape)
    print(df_elec[c].unique())
    print('-----------------------------')

In [ ]:
print(df_elec['Nom Officiel Région'].unique().shape)
df_elec['Nom Officiel Région'].unique()

In [ ]:
print(df_elec['Nom aménageur'].unique().shape)
df_elec['Nom aménageur'].unique()

In [ ]:
df_elec['Nom aménageur'].unique()

In [ ]:
df_elec['SIREN aménageur'].unique()

In [ ]:
df_elec['Puissance nominale'].unique()

In [ ]:
df_elec['Nombre Points de charge'].unique()

In [ ]:
df_elec.value_counts('Nombre Points de charge')

In [ ]:
df_elec.value_counts('Code INSEE commune')

In [ ]:
manquantes['Nom aménageur']

In [ ]:
# Valeurs manquantes
plt.figure(figsize=(22,9))
plt.bar(x= df_elec_analyse.sort_values(by='Nb_manquant',ascending=False)['Variable'], height = df_elec_analyse.sort_values(by='Nb_manquant',ascending=False)['Nb_manquant'])
plt.xticks(rotation=90)
plt.grid()
plt.ylabel('Valeurs Manquantes (-)')

In [ ]:
# Valeurs uniques par colonne
df_elec_analyse = []
manquantes = df_elec.isna().sum()
for t in df_elec.columns:
    row = {}
    row['Variable']=t
    row['type']= df_elec[t].dtypes
    row['Nb_val_unique']=len(df_elec[t].unique())
    row['Nb_manquant']=manquantes[t]
    df_elec_analyse.append(row)
df_elec_analyse = pd.DataFrame(df_elec_analyse)
df_elec_analyse

In [ ]:
df_elec_analyse.sort_values(by='Nb_val_unique',ascending=False)

In [ ]:
# Valeurs uniques
plt.figure(figsize=(22,9))
plt.bar(x= df_elec_analyse.sort_values(by='Nb_val_unique',ascending=False)['Variable'], height =df_elec_analyse.sort_values(by='Nb_val_unique',ascending=False)['Nb_val_unique'])
plt.xticks(rotation=90)
plt.grid()
plt.ylabel('Nb Valeurs Uniques (-)')

In [ ]:
df_elec[df_elec['Nombre Points de charge']==505]

In [ ]:
df_elec['Date mise en service'].unique()

In [ ]:
df_elec['Date mise en service'].unique())

In [10]:
cd C:\Users\plele\OneDrive - Université de Technologie de Troyes\Fil_rouge\

C:\Users\plele\OneDrive - Université de Technologie de Troyes\Fil_rouge

In [11]:
%pwd

'C:\\Users\\plele\\OneDrive - Université de Technologie de Troyes\\Fil_rouge'

In [12]:
df_elec_traite = pd.read_csv('.\Tables_traitees\Stations_electriques_avec_code_commune.csv',sep=';')

C:\Users\plele\AppData\Local\Temp\ipykernel_27952\125698992.py:1: DtypeWarning: Columns (12,52,63) have mixed types. Specify dtype option on import or set low_memory=False.
  df_elec_traite = pd.read_csv('.\Tables_traitees\Stations_electriques_avec_code_commune.csv',sep=';')

In [ ]:
df_elec_traite[:5]

In [17]:
# Valeurs uniques par colonne
df_elec_traite_analyse = []
manquantes = df_elec_traite.isna().sum()
for t in df_elec_traite.columns:
    row = {}
    row['Variable']=t
    row['type']= df_elec_traite[t].dtypes
    row['Nb_val_unique']=len(df_elec_traite[t].unique())
    row['Nb_manquant']=manquantes[t]
    df_elec_traite_analyse.append(row)
df_elec_traite_analyse = pd.DataFrame(df_elec_traite_analyse)
df_elec_traite_analyse.sort_values(by='Nb_manquant',ascending=False)

,Variable,type,Nb_val_unique,Nb_manquant
1,SIREN aménageur,float64,608,43077
47,consolidated_code_postal,float64,2649,41103
35,Num PDL,object,2797,38614
48,consolidated_commune,object,4200,37326
34,Raccordement,object,3,35250
27,Tarification,object,214,33502
12,Code INSEE commune,object,6034,32790
37,Observations,object,126,32150
39,cable_t2_attache,object,8,28767
8,ID station local,object,12850,21829
2,Contact aménageur,object,454,21544
16,ID PDC local,object,39325,20186
26,Paiement autre,float64,3,10203
3,Nom opérateur,object,211,8853
0,Nom aménageur,object,2670,8695
5,Téléphone opérateur,object,265,8447
25,Paiement CB,float64,3,2529
36,Date mise en service,object,2419,2407
32,Restriction gabarit,object,161,1616
58,Nom de l'EPCI,object,1136,106
57,Code EPCI,float64,1137,106
62,Nom Officiel Région,object,13,100
61,Code Officiel Région,float64,13,100
60,Nom Officiel Département,object,95,100
59,Code Officiel Département,float64,95,100
56,Code de la commune ou de l'arrondissement,float64,7458,100
55,Nom de la commune ou de l'arrondissement munic...,object,7379,100
63,code_commune_n,object,10757,55
23,Gratuit,float64,3,28
53,latitude,float64,17876,19
54,point_geo,object,18018,19
42,datagouv resource id,object,565,0
52,longitude,object,23716,0
51,coord,object,18019,0
50,consolidated_is_code_insee_verified,bool,2,0
49,consolidated_is_lon_lat_correct,bool,2,0
4,Contact opérateur,object,241,0
6,Nom enseigne,object,3950,0
46,consolidated_latitude,float64,17877,0
45,consolidated_longitude,float64,17930,0
44,created_at,object,565,0
43,datagouv organization or owner,object,228,0
19,Prise type 2,int64,2,0
20,Prise type combo ccs,int64,2,0
30,Horaires,object,545,0
21,Prise type chademo,int64,2,0
22,Prise type autre,int64,2,0
24,Paiement acte,int64,2,0
18,Prise type E/F,int64,2,0
17,Puissance nominale,int64,79,0
15,ID PDC itinérance,object,57798,0
28,Condition accès,object,2,0
29,Réservation,int64,2,0
31,Accessibilité PMR,object,4,0
40,Dernière modification,object,274,0
14,Nombre Points de charge,int64,55,0
33,Station deux roues,int64,2,0
13,Coordonnées,object,18655,0
11,Adresse station,object,18209,0
10,Implantation station,object,5,0
9,Nom station,object,18624,0
38,Date de Mise à Jour,object,698,0
7,ID station itinérance,object,19054,0
41,datagouv dataset id,object,509,0

In [21]:
df_communes_traite = pd.read_csv('.\Tables_traitees\Infos_communes_avec_prix_estimé.csv',sep=';')

C:\Users\plele\AppData\Local\Temp\ipykernel_27952\2387880232.py:1: DtypeWarning: Columns (2,10,17,18,26,27,35,50) have mixed types. Specify dtype option on import or set low_memory=False.
  df_communes_traite = pd.read_csv('.\Tables_traitees\Infos_communes_avec_prix_estimé.csv',sep=';')

In [22]:
# Valeurs uniques par colonne
df_communes_traite_analyse = []
manquantes = df_communes_traite.isna().sum()
for t in df_communes_traite.columns:
    row = {}
    row['Variable']=t
    row['type']= df_communes_traite[t].dtypes
    row['Nb_val_unique']=len(df_communes_traite[t].unique())
    row['Nb_manquant']=manquantes[t]
    df_communes_traite_analyse.append(row)
df_communes_traite_analyse = pd.DataFrame(df_communes_traite_analyse)
df_communes_traite_analyse.sort_values(by='Nb_manquant',ascending=False)

,Variable,type,Nb_val_unique,Nb_manquant
33,type,object,9,35990
55,delta_prix,float64,16782,10045
24,PrixMoyen_M2,float64,3709,9928
23,Nb_Ventes,float64,554,9928
34,Prix_estimé,float64,19720,1993
20,CODE_EPCI,float64,1237,1916
56,Prix_consolidé,float64,7894,1876
18,INSEE_DEP,object,98,1867
17,INSEE_COM,object,34884,1867
16,ID,object,34884,1867
21,NOM_COM_M,object,32430,1867
22,POPULATION,float64,5734,1867
26,code_commune_n,object,34884,1867
25,nb_digits_code_INSEE,float64,2,1867
19,INSEE_REG,float64,14,1867
27,insee,object,34938,1813
29,nb_voisins,float64,23,1813
30,insee_voisins,object,34935,1813
31,noms_voisins,object,34935,1813
32,cap_voisins,object,34932,1813
28,nom,object,32684,1813
15,Densité_hab_par_km2_x,float64,34724,823
11,Superficie de la commune,float64,5236,823
14,EPCI,object,2216,26
13,Code EPCI,object,2143,26
54,Densité_hab_par_km2_y,float64,18632,8
53,lon,float64,36743,8
52,lat,float64,36743,8
51,Code Région,float64,28,8
50,Code Département,object,99,8
40,Statut_y,object,28,8
48,Code Canton,float64,95,8
47,Code Commune,float64,909,8
46,ID Geofla,float64,36614,8
45,geo_shape,object,36743,8
44,geo_point_2d,object,36743,8
43,Population,float64,510,8
42,Superficie,float64,5247,8
41,Altitude Moyenne,float64,1653,8
49,Code Arrondissement,float64,11,8
39,Région,object,28,8
38,Département,object,102,8
37,Commune,object,34131,8
36,Code Postal,object,6102,8
35,Code INSEE,object,36743,8
3,Code commune,float64,908,0
4,Nom de la commune,object,34250,0
5,Population municipale,float64,5845,0
6,Population comptée à part,float64,793,0
7,Population totale,float64,5942,0
8,Année recensement,int64,10,0
1,Nom de la région,object,36,0
9,Année utilisation,int64,10,0
10,Code INSEE (commune ou arrondissement),object,36750,0
12,Statut_x,object,2,0
2,Code département,object,102,0
0,Code région,float64,34,0

## Stations carburants en France à J-7

https://public.opendatasoft.com/explore/dataset/prix_des_carburants_j_7/information/?sort=update

In [ ]:
df_carb = pd.read_csv(glob.glob('.\\Prix des carburants - J-7\\*.*')[0],sep=';')

In [ ]:
df_carb[:5]

In [ ]:
df_carb.columns

In [ ]:
df_carb.shape

In [ ]:
df_carb['Identifiant'].unique().shape

In [ ]:
df_carb['Identifiant'].unique()